apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http-metrics
    protocol: TCP
    name: http-metrics
  - port: 8081
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: vault-secrets-operator
