name: Docker

on: push

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Docker Image
        run: make docker-build

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: make docker-push
